version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    container_name: postgres
    environment:
      - bind-address=0.0.0.0
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      -  '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
      - ./db/initial.sql:/docker-entrypoint-initdb.d/create_tables.sql
      
  backend:
     build: ./backend
     depends_on:
       - db
     ports:
       - '5001:5001'
     volumes:
       - .:/src    
      
      
volumes:
  db:
    driver: local
